language: "perl"
perl:
#   - "5.10"
#   - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
install: "echo"
before_script:
    - cpanm -n IPC::Run B::Flags Opcodes IO::Socket::SSL LWP::UserAgent

script: "perl Makefile.PL && make && make test"

notifications:
  irc: "irc.perl.org#compiler"
  recipients:
    - perl-compiler@googlegroups.com
  email:
    on_success: change
    on_failure: always
