language: "perl"
perl:
    - "5.22.1"
install: "echo"
before_script:
    - perl -S cpanm Module::CPANfile
    - perl -S cpanm -n --installdeps .
    - cat t/v5.22.1/C-COMPILED/known_errors.ztravis.txt t/v5.22.1/C-COMPILED/known_errors.txt > known_tmp
    - mv known_tmp t/v5.22.1/C-COMPILED/known_errors.txt
script: "perl Makefile.PL && make testcore"
notifications:
  recipients:
    hipchat: uP9VHegFfhIDUiUdyIWDJInRFSnjIxqgqW4GFmOI@2022203
  email:
    on_success: change
    on_failure: always
# fast_finish: http://blog.travis-ci.com/2013-11-27-fast-finishing-builds/
matrix:
  fast_finish: true
# See https://blog.afoolishmanifesto.com/posts/use-travis-et-al/
before_install:
     - git clone git://github.com/haarg/perl-travis-helper
     - source perl-travis-helper/init
     - build-perl
     - perl -V
     - build-dist
     - cd $BUILD_DIR
